// Generate emit test runner for Elixir roundtrip tests
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dir = path.dirname(fileURLToPath(import.meta.url));
const VEC_DIR = process.env.VEC_DIR || path.join(__dir, ".tests-cache", "vectors");

const manifestPath = path.join(VEC_DIR, "manifest.json");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));

const models = [...(manifest.testModels || []), ...(manifest.testUnions || [])];
const scalars = manifest.scalars || {};
const modelNamespaces = manifest.modelNamespaces || {};
const testUnions = new Set(manifest.testUnions || []);
function isUnionTest(name) { return testUnions.has(name); }
function unionNameOf(testName) { return testName.replace(/_[^_]+$/, ""); }

function toSnakeCase(name) {
  return name.replace(/([A-Z])/g, "_$1").toLowerCase().replace(/^_/, "").replace(/\./g, "_").replace(/-/g, "_");
}
function toPascalCase(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function scalarRead(type) {
  const m = { int32: "read_int32", int64: "read_int64", uint32: "read_uint32", uint64: "read_uint64", float32: "read_float32", float64: "read_float64", string: "read_string", bytes: "read_bytes", bool: "read_bool" };
  return m[type] || "read_int32";
}
function scalarWrite(type) {
  const m = { int32: "write_int32", int64: "write_int64", uint32: "write_uint32", uint64: "write_uint64", float32: "write_float32", float64: "write_float64", string: "write_string", bytes: "write_bytes", bool: "write_bool" };
  return m[type] || "write_int32";
}

function modelTestFunc(model) {
  const snake = toSnakeCase(model);
  const codecName = isUnionTest(model) ? unionNameOf(model) : model;
  return `
def test_${snake}(vec, out) do
  passed = 0
  failed = 0

  # MsgPack
  try do
    expected = File.read!(Path.join(vec, "${model}.msgpack"))
    reader = MsgPackReader.new(expected)
    {obj, _r} = ${codecName}.decode(MsgPackReader, reader)
    writer = MsgPackWriter.new()
    w = ${codecName}.encode(MsgPackWriter, writer, obj)
    actual = MsgPackWriter.to_bytes(w)
    if actual == expected, do: passed = passed + 1, else: (failed = failed + 1; IO.puts(:stderr, "FAIL ${model} mp"))
  rescue
    e -> failed = failed + 1; IO.puts(:stderr, "FAIL ${model} mp: #{Exception.message(e)}")
  end

  # JSON
  try do
    expected = File.read!(Path.join(vec, "${model}.json"))
    reader = JsonReader.new(expected)
    {obj, _r} = ${codecName}.decode(JsonReader, reader)
    writer = JsonWriter.new()
    w = ${codecName}.encode(JsonWriter, writer, obj)
    actual = JsonWriter.to_bytes(w)
    if actual == expected, do: passed = passed + 1, else: (failed = failed + 1; IO.puts(:stderr, "FAIL ${model} json"))
  rescue
    e -> failed = failed + 1; IO.puts(:stderr, "FAIL ${model} json: #{Exception.message(e)}")
  end

  # Unformatted JSON
  try do
    expected = File.read!(Path.join(vec, "${model}.unformatted.json"))
    reader = JsonReader.new(expected)
    {obj, _r} = ${codecName}.decode(JsonReader, reader)
    writer = JsonWriter.new()
    w = ${codecName}.encode(JsonWriter, writer, obj)
    actual = JsonWriter.to_bytes(w)
    if actual == expected, do: passed = passed + 1, else: (failed = failed + 1; IO.puts(:stderr, "FAIL ${model} unformatted"))
  rescue
    e -> failed = failed + 1; IO.puts(:stderr, "FAIL ${model} unformatted: #{Exception.message(e)}")
  end

  # Gron
  try do
    expected = File.read!(Path.join(vec, "${model}.gron"))
    reader = GronReader.new(expected)
    {obj, _r} = ${codecName}.decode(GronReader, reader)
    writer = GronWriter.new()
    w = ${codecName}.encode(GronWriter, writer, obj)
    actual = GronWriter.to_bytes(w)
    if actual == expected, do: passed = passed + 1, else: (failed = failed + 1; IO.puts(:stderr, "FAIL ${model} gron"))
  rescue
    e -> failed = failed + 1; IO.puts(:stderr, "FAIL ${model} gron: #{Exception.message(e)}")
  end

  {passed, failed}
end`;
}

const outDir = path.join(__dir, "emit");
fs.mkdirSync(outDir, { recursive: true });

// Generate test file
let body = `# Generated by generate_emit_runner.mjs. DO NOT EDIT.
defmodule EmitRunner do
alias Specodec.Generated.{
${models.map(m => `  ${isUnionTest(m) ? unionNameOf(m) : m}`).join(",\n")}
}
alias Specodec.{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter}

`;

// Scalars
const scalarTests = [];
for (const [name, info] of Object.entries(scalars)) {
  const snake = toSnakeCase(name);
  body += `
def test_${snake}(vec, out) do
  try do
    expected = File.read!(Path.join(vec, "scalars/${name}.mp"))
    reader = MsgPackReader.new(expected)
    {val, _r} = MsgPackReader.${scalarRead(info.type)}(reader)
    writer = MsgPackWriter.new()
    w = MsgPackWriter.${scalarWrite(info.type)}(writer, val)
    actual = MsgPackWriter.to_bytes(w)
    File.mkdir_p!(Path.join(out, "scalars"))
    File.write!(Path.join(out, "scalars/${name}.mp"), actual)
    if actual == expected, do: {1, 0}, else: {0, 1}
  rescue
    e -> IO.puts(:stderr, "FAIL ${name}: #{Exception.message(e)}"); {0, 1}
  end
end
`;
  scalarTests.push(name);
}

// Models
for (const model of models) {
  body += modelTestFunc(model);
}

// Runner
body += `
def run_all(vec, out) do
  File.mkdir_p!(out)
  passed = 0
  failed = 0
`;

for (const name of Object.keys(scalars)) {
  const snake = toSnakeCase(name);
  body += `  {p, f} = test_${snake}(vec, out); passed = passed + p; failed = failed + f\n`;
}
for (const model of models) {
  const snake = toSnakeCase(model);
  body += `  {p, f} = test_${snake}(vec, out); passed = passed + p; failed = failed + f\n`;
}

body += `
  IO.puts("emit-elixir: #{passed} passed, #{failed} failed")
  if failed > 0, do: System.halt(1)
end

end

vec = System.get_env("VEC_DIR")
out = System.get_env("OUT_DIR")
EmitRunner.run_all(vec, out)
`;

fs.writeFileSync(path.join(outDir, "test_runner.exs"), body);
console.log(`Generated emit/test_runner.exs with ${models.length} models and ${Object.keys(scalars).length} scalars`);
